### ISSUE TITLE
Quick comments

### ISSUE THREAD

**Issue by RohanAlexander** [aj3616/Forecasting-the-US-Election-2024#1]
- "Forcasting" is a typo? Should be "Forecasting"
- Overview - Need to know what your results are. R should be capitalized.
- Remove unused scripts e.g. https://github.com/aj3616/Forcasting-US-Election-2024/blob/main/scripts/00-simulate_data.py
- Title - "Forcasting US Election 2024" - there's a missing "the" right? "Forcasting the US Election 2024"
- First paragraph needs to be split into a two or three.
- Captions: Please don't say "Graph of".
- You don't need both a title and a caption. Just have a caption and make it really informative.
- Figure 2 - State names can't be read. Fix.
- References need work. Check the names e.g. natesilver and capitalization e.g. Gt should be gt.

**Comment by aj3616** [comment]
Thank you professor! Fixed!
