### ISSUE TITLE
Peer Review - Sarah Ding (Group19)

### ISSUE THREAD

**Issue by sarahdingg** [aj3616/Forecasting-the-US-Election-2024#7]
*Summary:
This paper explains the polling strategies that different pollsters use by providing a thorough explanation as well as data visualizations. The appendix contains relevant information on the polling methodology adopted by YouGov and discussions about the quality of data and surveys.

*Strong Positive Points:
**Background information
Good job on providing a clear background explanation of how polling works, especially how different pollsters adopt different methodologies which could affect the quality of the results. There is also a clear explanation of the different variables from the raw data set such as poll_id.

**Clear Structure
There is a clear structure throughout the paper, each part is clearly labeled to explain what the purpose is. 

*Critical Improvements Needed:
**Completion of paper
The abstract is missing, which is crucial, it provides the readers a general idea of what the paper is going to explore, what the results are, and how you came to the conclusion.

The parts talking about variables, the model section, the results section, and the discussion section are all missing. Without all of these, the paper is incomplete and readers wouldn't understand what approach you are taking to predict the outcome of the election. You could try using a Bayesian Linear Model to get started. I also suggest pinpointing the approach that you want to take in terms of selecting variables and models to predict the outcome. 

**Choosing an approach
It seems like there is no clear approach to the kind of model you want to use or the variables you want to use to predict the outcome. I suggest making a decision on whether you want to analyze data based on state-level pct of support or nationwide pct of support. 
  

*Suggestions for Improvement:
**Problems with data visualization
Table 3 has some formatting issues where the second half of the table is cut off onto a second page. Figure 2 looks too crowded, so maybe consider using fewer data points to compute the graph. I suggest cleaning the raw data set more thoroughly so that you are only left with the data points you need to explain your point. 

**Interpretation of the data
Please include some kind of interpretation or explanation for all the data visualizations, for example, for graph 4, I suggest explaining the significance of graphing the sponsorships of the two candidates

**Consistent formatting
I suggest keeping the formatting of the paper consistent, especially with the data visualizations, as well as how the paragraphs are structured, it would make the paper look cleaner and easy for the reader to read and understand. 

*Evaluation:
R is appropriately cited: 1/1
Data are appropriately cited: 1/1
Class paper: 1/1
LLM usage is documented: 0/1
Title: 1/2
Author, date, and repo: 2/2
Abstract: 0/4
Introduction: 1/4
Estimand: 0/1
Data: 5/10
Measurement: 0/4
Model: 0/10
Results: 0/10
Discussion: 0/10
Prose: 4/6
Cross-references: 0.5/1
Captions: 0.5/2
Graphs/tables/etc: 2/4
Idealized methodology: 0/10
Idealized survey: 0/4
Pollster methodology overview and evaluation: 6/10
Referencing: 3/4
Commits: 2/2
Sketches: 0/2
Simulation: 1/4
Tests-simulation: 1/4
Tests-actual: 1/4
Parquest: 0/1
Reproducible workflow: 1/4
Miscellaneous: 1/3

Estimated overall mark:  32/126

Additional Comments:
Overall, the paper is incomplete and missing some very crucial sections such as model, results, and discussion, as well as the second appendix of idealized methodology. There is good explanation of the background information regarding the methodology of different pollsters but it is not the main focus of the paper. I hope that with more completed sections, the paper will excel!

**Comment by aj3616** [comment]
Thank you for the comments!
