### ISSUE TITLE
Peer review from group 108

### ISSUE THREAD

**Issue by YizheChenUT** [aj3616/Forecasting-the-US-Election-2024#8]
**Summary:**
The paper Forecasting US Election 2024 uses polling data and statistical modeling to predict the outcome of the 2024 U.S. Presidential election. The model focuses on polling data, evaluating the accuracy of different polling methodologies and analyzing key variables, such as sample size and pollster reliability. The paper highlights the importance of polling in shaping electoral strategies and includes state-level breakdowns of polling results for key battleground states.

**Strong positive points:**
- Comprehensive Dataset: The paper uses a large dataset of polling information that allows for detailed analysis of voter trends and polling methodologies.
- Methodology Comparison: It offers a robust comparison of different polling methodologies, analyzing their influence on predicted vote percentages for Kamala Harris and Donald Trump.
- Focus on State-Level Analysis: The inclusion of state-by-state polling trends in battleground states enhances the relevance of the analysis for understanding election dynamics.

**Critical improvements needed:**
- Unfinished Sections: The paper contains placeholders, such as "TODO" sections, which need to be completed, particularly the results and some detailed explanations.
- Model Justification: While the paper presents a Bayesian model, more justification is needed for its selection over other potential models. A comparison of model performances or reasons why a Bayesian approach was chosen would strengthen this section.
- More Detailed Discussion on Assumptions: The paper lacks an in-depth discussion of the assumptions underlying the model and potential biases in polling data. This should be addressed to clarify the model’s limitations.
- Figure 2 - State names are crowded
- Commit messages not adequate and informative.
- Some grammatical errors exist.
- `other/llm/usage.txt`  `usage.txt` is not updated.

**Suggestions for improvement:**
- Complete the Results Section: Ensure that the final results are included, with clear analysis and visual representation of the outcomes.
- Add More Context to Model Justification: Provide more context around why specific modeling decisions were made, including the choice of Bayesian methods and assumptions about voter behavior.
- Visualization Improvements: Add more graphs, tables, and figures to support the findings.  And, fix Figure 2 - State names are crowded.
- Enhance the Discussion of Methodology: Expand on the details of polling methodology and its influence on the outcomes. This section could benefit from a more thorough explanation of how different methods (e.g., online vs. phone polling) affect voter support predictions.
- Address Polling Biases: Include a discussion of potential polling biases and explain how the model accounts for these.
- Improve quality of commit messages
- Remove unused scripts

**Evaluation:**
R is appropriately cited: [1/1 pts]  R is properly referenced.
Data are appropriately cited: [1/1 pts] Polling data sources are referenced.
Class paper: [1/1 pts] No indications show this is a class paper.
LLM usage is documented: [0/1 pts] `other/llm/usage.txt`  `usage.txt` is not updated.
Title: [1/2 pts] The title is descriptive but could be specific to highlight model and forecast approach used.
Author, date, and repo: [2/2 pts] Clearly stated, with a link to the GitHub repo.
Abstract: [0/4 pts] Need to be completed.
Introduction: [3/4 pts] The introduction is generally clear but could better outline the significance of the model used.
Estimand: [0/1 pts] The estimand is not clearly defined.
Data: [8/10 pts] The data section is detailed but lacks a deeper discussion of data cleaning and variable transformations.
Measurement: [3/4 pts] Good, but the paper could expand on how measurements were validated.
Model: [7/10 pts] The model is well-defined, but more justification for the Bayesian approach would strengthen the analysis.
Results: [3/10 pts] Results are incomplete, with several sections left unfinished or marked as placeholders.
Discussion: [5/10 pts] The discussion is somewhat lacking and could be more comprehensive, particularly regarding limitations and implications.
Prose: [4/6 pts] Writing is generally clear, but placeholders and some grammatical errors need attention.
Cross-references: [1/1 pts] Cross-references are used appropriately.
Captions: [1/2 pts] Some figures lack clear captions, and avoid using "Graph of".
Graphs/tables/etc: [3/4 pts] The paper includes some visual aids but could benefit from additional charts and tables.
Idealized methodology: [0/10 pts] Missing idealized methodology
Idealized survey: [0/4 pts] Missing idealized survey
Pollster methodology overview and evaluation: [8/10 pts] A good overview, but could go deeper into potential pollster biases.
Referencing: [4/4 pts] All data and methods are properly referenced.
Commits: [1/2 pts] Commit messages not adequate and informative
Sketches: [0/2 pts] Sketches are not updated.
Simulation: [4/4 pts] Solid simulation setup
Tests - simulation: [4/4 pts] 
Tests - actual: [4/4 pts] 
Parquet: [0/1 pts] Analysis data not in parquet format.
Reproducible workflow: [3/4 pts] Well-organized, though documentation could be improved.
Miscellaneous: [0/3 pts]

**Estimated overall mark:**
72 out of 126.

**Any other comments:**
This paper has potential, but key sections need to be completed and expanded. The Bayesian model is a good choice, but more justification for its use would improve the analysis. Additionally, the results section needs to be finalized, and more visualizations should be included to better illustrate the findings.

**Comment by aj3616** [comment]
Thank you for the comments!
